name: Scala CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'project/*'
      - 'src/**/*'
      - '.scalafmt.conf'
      - 'build.sbt'
  pull_request:
    branches: [ main ]
    paths: 
      - 'project/*'
      - 'src/**/*'
      - '.scalafmt.conf'
      - 'build.sbt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build 
      run: sbt compile
